-- AlterEnum
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'PENDING_VALIDATION';

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isBanned" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bannedAt" TIMESTAMP(3);
